### ISSUE TITLE
[OFFICIAL] Generated Issue: ParserException

### ISSUE THREAD

**Issue by sa-met** [jikan-me/jikan#435] opened 2022-06-20 09:16 UTC
Please fill out the details below.

**Summary:**

**Steps to reproduce:**

 ### Additional Details 
 **Jikan Parser Version**: ```3.0.0.x-dev@3803cc1b882baf7b95d4e90fba4bb871c0cf8dc0```
**PHP:** ```8.0.19```
**Redis**: ```Connected```
**Exception:** ```Jikan\Exception\ParserException```
**Code:** ```0```
**Message:** ```Failed to parse 'https://myanimelist.net/anime/38992/_/episode?offset=0'```
**Trace:** ```/var/www/jikan-rest/vendor/jikan-me/jikan/src/Exception/ParserException.php on line 24```
**Request:** `GET /v4/anime/38992/episodes?0=1`
"

**Comment by nerg4l** [comment] 2022-06-20 10:23
Duplicate of #400

**Closed by nerg4l** 2022-06-20 10:23 UTC
