### ISSUE TITLE
[SEARCH] Search by all titles, not just by the main one.

### ISSUE THREAD

**Issue by Wamy-Dev** [jikan-me/jikan#482] opened 2022-10-09 19:05 UTC
I think it would help out a lot if the search were to search by all the titles in the {titles} object rather than just searching for the main title. I have anime data with names that aren't quite the real names, but they show up in the synonyms or in "title_english" and I think it would greatly benefit everyone to get the most accurate search if we were able to search by any title in that object.

**Comment by irfan-dahir** [comment] 2022-10-10 00:23
Hi, were working on this

Closing as it's a duplicate of https://github.com/jikan-me/jikan-rest/issues/189 and https://github.com/jikan-me/jikan-rest/issues/235

**Closed by irfan-dahir** 2022-10-10 00:23 UTC
