### ISSUE TITLE
[OFFICIAL] Generated Issue: ParserException

### ISSUE THREAD

**Issue by ArrowPC** [jikan-me/jikan#434] opened 2022-06-19 14:52 UTC
Please fill out the details below.

**Summary:**

Episodes fail to parse with some anime such as Psycho-Pass and Hyouka

**Steps to reproduce:**

Step 1. 
```zsh
curl https://api.jikan.moe/v4/anime/13601/episodes
```

Step 2.
***Status 500***

 ### Additional Details 
 **Jikan Parser Version**: ```3.0.0.x-dev@3803cc1b882baf7b95d4e90fba4bb871c0cf8dc0```
**PHP:** ```8.0.19```
**Redis**: ```Connected```
**Exception:** ```Jikan\Exception\ParserException```
**Code:** ```0```
**Message:** ```Failed to parse 'https://myanimelist.net/anime/13601/_/episode?offset=0'```
**Trace:** ```/var/www/jikan-rest/vendor/jikan-me/jikan/src/Exception/ParserException.php on line 24```
**Request:** `GET /v4/anime/13601/episodes`

**Comment by nerg4l** [comment] 2022-06-20 10:22
Duplicate of #400

**Closed by nerg4l** 2022-06-20 10:22 UTC
