### ISSUE TITLE
Only the first character is returned for characters_staff request

### ISSUE THREAD

**Issue by mozgow** [jikan-me/jikan#362] opened 2021-09-11 12:07 UTC
When requesting characters_staff data only the first character is returned.

Eg.: https://api.jikan.moe/v3/anime/16/characters_staff returns only one character, "Hanamoto, Hagumi", but the anime has many more. See: [Hachimitsu to Clover characters page](https://myanimelist.net/anime/16/Hachimitsu_to_Clover/characters)

Most likely caused by fix for #361.

**Comment by mozgow** [comment] 2021-09-11 12:27
The problems are probably caused by this update on MAL: [Sort & Filter Functions Added: Characters, VAs](https://myanimelist.net/forum/?topicid=1955276)

**Comment by irfan-dahir** [comment] 2021-09-11 12:53
Yes, it was caused by that update. It's been resolved in https://github.com/jikan-me/jikan/releases/tag/v2.16.27

However, some endpoints are still cached with the old response and are showing that.

I've deleted the existing cache for https://api.jikan.moe/v3/anime/16/characters_staff
So you see the appropriate response now 👌

**Comment by mozgow** [comment] 2021-09-11 13:33
It's seem to be ok now for "Hachimitsu to Clover". 
How long till all the caches are refreshed ?

**Comment by irfan-dahir** [comment] 2021-09-11 13:41
It's usually 24 hours but recently due to the DDoS, I've bumped it to 48 hours. 
IDK which other caches are affected, but if you find any then feel free to ping me. I'll invalidate them. Can leave this issue open for 2 days.

**Comment by Ammourie** [comment] 2021-09-12 13:12
> It's usually 24 hours but recently due to the DDoS, I've bumped it to 48 hours.
> IDK which other caches are affected, but if you find any then feel free to ping me. I'll invalidate them. Can leave this issue open for 2 days.
I think  manga characters is affected also 
it returns empty list of characters
it was working before
https://api.jikan.moe/v3/manga/121496/characters

**Comment by irfan-dahir** [comment] 2021-09-12 13:40
Good catch @Ammourie , I completely forgot about manga. Pushed a fix, which would work as soon as the cache invalidates.

**Comment by mozgow** [comment] 2021-09-18 13:52
I think the issue can be closed now :)

**Closed** 2021-09-18 13:55 UTC
