### ISSUE TITLE
BadResponseException in search character

### ISSUE THREAD

**Issue by moepoi** [jikan-me/jikan#289] opened 2020-06-13 10:20 UTC
> {
>   "status": 403,
>   "type": "BadResponseException",
>   "message": "Jikan failed to connect to MyAnimeList. MyAnimeList may be down/unavailable or refuses to connect",
>   "error": "403 on https://myanimelist.net/character.php?q=sakuranomiya+maika"
> }

- https://api.jikan.moe/v3/search/character?q=sakuranomiya+maika&page=1

**Comment by irfan-dahir** [comment] 2020-06-13 11:39
Ongoing issue. Check this out:
https://github.com/jikan-me/jikan-rest/issues/102#issuecomment-640101348

Closing; duplicate of https://github.com/jikan-me/jikan-rest/issues/102

**Closed by irfan-dahir** 2020-06-13 11:39 UTC
