### ISSUE TITLE
Documentation for titles property is incorrect

### ISSUE THREAD

**Issue by JoshuaWalsh** [jikan-me/jikan#473] opened 2022-08-30 09:23 UTC
The documentation for [getAnimeFullById](https://docs.api.jikan.moe/#tag/anime/operation/getAnimeFullById) and [getAnimeById](https://docs.api.jikan.moe/#tag/anime/operation/getAnimeById) says that the "titles" property contains an array of strings.

This property actually contains an array of objects, with each object containing "type" and "title" properties.

**Comment by nerg4l** [comment] 2022-08-30 09:29
Duplicate of jikan-me/jikan#266

**Comment by nerg4l** [comment] 2022-08-30 09:30
Duplicate of jikan-me/jikan-rest#266

**Closed by nerg4l** 2022-08-30 09:29 UTC

**Comment by JoshuaWalsh** [comment] 2022-08-30 09:33
Is jikan-rest the v4 project? Should I move my other reported issues to that project too?

**Comment by nerg4l** [comment] 2022-08-30 17:22
`jikan-me/jikan` contains the parsers which fetch data from MAL and create PHP objects. If the problem is related to parsing or accessing MAL then you should open an issue for `jikan-me/jikan`.

Compared to that, `jikan-me/jikan-rest` contains a REST API which exposes those parsed objects. If the problem is related to schema or REST API the you should open an issue for jikan-me/jikan-rest`.

Because not everyone knows this, you can open issues in any of them and we will manage them accordingly.
