### ISSUE TITLE
API Character/Person Endpoint Anomalies

### ISSUE THREAD

**Issue by cdterry87** [jikan-me/jikan#201] opened 2018-09-27 02:11 UTC
I've been working with the API and I've run into a few strange occurrences, and I'm not sure if they are issues or if there is a logical explanation for what I'm experiencing.

For example, if I try to hit the following endpoint: **https://api.jikan.moe/search/character/goku**

I receive the expected result - a status of 200 and a JSON string with information for the character Goku.

However, if I try to hit this endpoint: **https://api.jikan.moe/search/character/bulma**

I receive a 500 status with an error in the console that just says "Server error" even though I know "Bulma" is a valid character.

If I change "bulma" to "buruma" (the Japanese pronounciation of Bulma) so it looks like this: **https://api.jikan.moe/search/character/buruma** I do receive the expected result - a 200 status and Bulma's information.  The result even has "Bulma" in the name field.  This leads me to believe the endpoint is potentially searching based on the "nickname" field rather than the "name" field but it's just a guess.  I just thought it was strange that it couldn't pull "Bulma" and there are a few other names I tried that didn't work, as well.

-------------

On a related note, a similar thing seems to be happening for certain voice actors.  If I search for Monica Rial at the following endpoint, I receive a 200 status with the relevant search results: **https://api.jikan.moe/search/people/rial**

But if I do a similar search looking for Vic Mignogna at the following endpoint, I get a status of 200, but no results at all: **https://api.jikan.moe/search/people/mignogna**

Is there something special I should be doing when searching for voice actors using the API?  I also noticed I can search for something like "Dragon Ball Z" with the https://api.jikan.moe/search/anime/:name endpoint, but I can't do a similar search like "Monica Rial" with the https://api.jikan.moe/search/people/:name endpoint.  I'm just not sure if there's something extra I should be doing to be able to pull better results from the voice actor/person/people part of the API.

I apologize if this isn't the correct place to post this, or if this is just user error.  It's entirely possible that I'm doing something wrong, but I just wanted to post in case it is an issue or just to receive clarification on what I might be doing wrong.  Thank you in advance for any help you can provide!

**Comment by irfan-dahir** [comment] 2018-09-27 06:38
Hi, thank you for opening an elaborate issue.

The first one ("Bulma" character search) is actually a parser issue related to #198 and #200. We changed how the MAL IDs are to be parsed from URLs a bit back and MAL has buggy/empty links (see image). This causes the parser to throw an exception, which gives "Server Error" on the REST service. 
![screenshot from 2018-09-27 10-37-57](https://user-images.githubusercontent.com/9166451/46125322-060dd500-c242-11e8-9a46-0e672005adfd.png)

I've patched the the MAL URL parser to return `0` for MAL IDs for these "empty links". So https://api.jikan.moe/search/character/bulma should work. Currently looking into a permanent solution going forward and into why "Server Error" is being shown instead of the parser error on the REST service.

---
The latter part of your issues are both actually caused by the same problem. What MAL does when there's only 1 search result is that it redirects to that item's page instead of listing the singular result.

So as an example, Jikan parses people from this MAL link: `myanimelist.net/people.php?q=` Hence both "Mignogna" and "Monica Rial" are plugged into there.
If you go to these link, you'll see the result**s**: 
- https://myanimelist.net/people.php?q=rial 
- https://myanimelist.net/anime.php?q=Dragon%20Ball%20Z

However links that only have single results are redirected. Try these search links as an example, you'll be taken to their pages instead. 
- https://myanimelist.net/people.php?q=mignogna 
- https://myanimelist.net/people.php?q=Monica%20Rial

I'm currently working on a solution to tackle this by following the redirection and parsing it as a result item. I've opened an issue which can be tracked; #202.

---
Also two more things.
- The base version you're using is currently v2. You can use REST v3 via `https://api.jikan.moe/v3/` which has many more features but a [Schema Update](https://github.com/jikan-me/jikan-rest/blob/master/MIGRATION.MD) as well.
- It's encouraged to use the search endpoint by putting your query in the `?q=` GET. Search results are more accurate this way, percentage encoding is fully supported and characters such as `/` can be included.
- https://api.jikan.moe/v3/search/character/?q=goku
- https://api.jikan.moe/v3/search/anime/?q=Dragon%20Ball%20Z

And for pagination
- https://api.jikan.moe/v3/search/people/?q=rial&page=2

More information here: https://jikan.docs.apiary.io/#reference/0/search


Let me know if I can help you any further

**Comment by cdterry87** [comment] 2018-09-29 15:15
Thank you for getting back to me so quickly with a fix and for explaining the issues!  That actually makes a lot of sense now.  

And thanks for letting me know about the v3 update.  I'm actually working on a small application that reads from the API so sometime soon I will likely migrate my code over to that version after checking out the documentation.

Thanks again for all your help!

**Comment by irfan-dahir** [comment] 2018-09-29 15:38
Anytime!

Closing this, you can track #202 with the remaining issue.

**Closed by irfan-dahir** 2018-09-29 15:38 UTC
